scalar Timestamp

enum Operation {
    ADD
    REMOVE
    UPDATE
}

enum Status {
    SUCCESS
    FAILURE
}

interface IResponse {
    id: ID!
}

type ErrorRes {
    error: Error!
}

type Error {
    error: String!
}

type SignInSuccessRes {
    bearer_token: String!
}

type SignUpSuccessRes {
    created_at: Timestamp
}

type SignOutSuccessRes implements IResponse {
    id: ID!
}

type ForgotPasswordSuccessRes implements IResponse {
    id: ID!
}

type ResetPasswordSuccessRes {
    data: ResetPasswordData!
}

type AddFavoriteSuccessRes {
    data: CreateData!
}

type GetAllUserFavoritesSuccessRes {
    data: [GetUserFavoritesData!]!
}

type DeleteFavoriteSuccessRes {
    data: DeleteFavoriteData!
}

type AddCartSuccessRes {
    data: CreateData!
}

type GetUserCartsSuccessRes {
    data: [CartData!]!
}

type UpdateCartSuccessRes {
    data: UpdateData!
}

type RemoveCartSuccessRes {
    data: RemoveCartData!
}

type AddProductSuccessRes {
    data: CreateData!
}

type UpdateProductSuccessRes {
    data: UpdateData!
}

type GetProductsSuccessRes {
    data: GetProductsData!
}

type GetProductSuccessRes {
    data: ProductData!
}

type RemoveProductSuccessRes {
    data: RemoveData!
}

type UpdateProductCategoriesSuccessRes {
    data: UpdateData!
}

type UpdateProductImagesSuccessRes {
    data: UpdateData
}

type AddOrderSuccessRes {
    data: CreateData!
}

type GetOrdersSuccessRes {
    data: OrdersData!
}

type GetUserOrdersSuccessRes {
    data: UserOrderData!
}

type GetOrderSuccessRes {
    data: GetOrderData!
}

type PaymentIntentSuccessRes {
    data: PaymentIntentData!
}

type PaymentIntentData {
    client_secret: String!
}

type UpdatePaymentIntentSuccessRes {
    data: PaymentIntentData!
}

type ConfirmPaymentIntentSuccessRes {
    data: ConfirmPaymentIntentData!
}

type PaymentWebhookSuccessRes {
    data: PaymentWebhookData!
}

type PaymentWebhookData {
    event_id: String!
    event_type: String!
    payment_status: Status!
    order_id: String!
}

type ConfirmPaymentIntentData {
    confirmed: Boolean!
}

type GetOrderData {
    id: ID!
    address: String!
    nearby_landmark: String!
    products: [ProductsData!]!
    total_amount: Float!
    status_payment: String!
    created_at: Timestamp!
}

type UserOrderData {
    id: ID!
    created_at: Timestamp!
    status_payment: String!
    total_amount: Float!
    currency: String!
    uri: String!
}

type OrdersData {
    page: Int!
    limit: Int!
    total_pages: Int!
    total_items: Int!
    orders: [OrderData!]!
}

type OrderData {
    order_id: ID!
    customer: CustomerData!
    address: String!
    nearby_landmark: String!
    products: ProductsData!
    total_amount: Float!
    status_payment: String!
    created_at: Timestamp!
}

type ProductsData {
    product_id: String!
    name: String!
    quantity: Int!
    unit_price: Float!
    total_price: Float!
    uri: String!
}

type CustomerData {
    id: ID!
    name: String!
    email: String!
}

type GetProductsData {
    page: Int!
    limit: Int!
    total_pages: Int!
    total_items: Int!
    products: [Product!]!
}

type ProductData {
    id: ID!
    name: String!
    description: String!
    stock: Int!
    is_available: Boolean!
    unit_price: Float!
    currency: String!
    image_url: String!
}

type Product {
    id: ID!
    name: String!
    categories: [ID!]!
    unit_price: Float!
    currency: String!
    image_url: String!
    uri: String!
}

type StandardBadRequestData {
    field: String!
}

type RemoveData {
    id: ID!
}


type ResetPasswordData {
    id: ID!
}

type CreateData {
    id: ID!
    created_at: Timestamp!
}

type DeleteFavoriteData {
    id: ID!
}

type RemoveCartData {
    id: ID!
}

type CartData {
    id: ID!
    product_id: ID!
    product_name: String!
    unit_price: Float!
    currency: String!
    image_url: String!
    uri: String!
}

type UpdateData {
    id: ID!
    updated_at: Timestamp!
}

type GetUserFavoritesData {
    id: ID!
    product_id: ID!
    product_name: String!
    unit_price: Float!
    currency: String!
    image_url: String!
    uri: String!
}

input PaymentWebhookInputData {
    status: Status!
    amount_received: Int!
    metadata: MetaData
}

input MetaData {
    order_id: ID!
}

type DataError {
    error: String!
}

union SignInRes = SignInSuccessRes | ErrorRes
union SignUpRes = SignUpSuccessRes | ErrorRes
union SignOutRes = SignOutSuccessRes | ErrorRes
union ForgotPasswordRes = ForgotPasswordSuccessRes | ErrorRes
union ResetPasswordRes = ResetPasswordSuccessRes | ErrorRes
union AddFavoriteRes = AddFavoriteSuccessRes | ErrorRes
union GetAllUserFavoritesRes = GetAllUserFavoritesSuccessRes | ErrorRes
union DeleteFavoriteRes = DeleteFavoriteSuccessRes | ErrorRes
union AddCartRes = AddCartSuccessRes | ErrorRes
union GetUserCartsRes = GetUserCartsSuccessRes | ErrorRes
union UpdateCartRes = UpdateCartSuccessRes | ErrorRes
union RemoveCartRes = RemoveCartSuccessRes | ErrorRes
union AddProductRes = AddProductSuccessRes | ErrorRes
union UpdateProductRes = UpdateProductSuccessRes | ErrorRes
union RemoveProductRes = RemoveProductSuccessRes | ErrorRes
union GetProductsRes = GetProductsSuccessRes | ErrorRes
union GetProductRes = GetProductSuccessRes | ErrorRes
union UpdateProductCategoriesRes = UpdateProductCategoriesSuccessRes | ErrorRes
union UpdateProductImagesRes = UpdateProductImagesSuccessRes | ErrorRes
union AddOrderRes = AddOrderSuccessRes | ErrorRes
union GetOrdersRes = GetOrdersSuccessRes | ErrorRes
union GetUserOrdersRes = GetUserOrdersSuccessRes | ErrorRes
union GetOrderRes = GetOrderSuccessRes | ErrorRes
union CreatePaymentIntentRes = PaymentIntentSuccessRes | ErrorRes
union UpdatePaymentIntentRes = UpdatePaymentIntentSuccessRes | ErrorRes
union ConfirmPaymentIntentRes = ConfirmPaymentIntentSuccessRes | ErrorRes
union PaymentWebhookRes = PaymentWebhookSuccessRes | ErrorRes

input SignInReq {
    email: String!
    password: String!
}

input SignUpReq {
    first_name: String!
    last_name: String!
    email: String!
    address: String!
    password: String!
}

input ForgotPasswordReq {
    email: String!
}

input ResetPasswordReq {
    token: String!
    new_password: String!
}

input AddFavoriteReq {
    product_id: ID!
}

input DeleteFavoriteReq {
    id: ID!
}

input AddCartReq {
    product_id: ID!
    quantity: Int!
}

input UpdateCartReq {
    op: Operation!
    path: String!
    value: Int!
}

input AddProductReq {
    product_name: String!
    description: String!
    stock: Int!
    categories: [ID!]!
    is_available: Boolean!
    image_url: String!
    unit_price: Float!
}

input UpdateProductReq {
    name: String!
    price: Float!
    description: String!
    stock: Int!
    is_available: Boolean!
}

input GetProductsReq {
    first: Int!
    after: ID!
}

input GetOrdersReq {
    first: Int!
    after: ID!
}

input UpdateProductCategoriesReq {
    op: Operation!
    path: String!
    value: [ID!]!
}

input UpdateProductImagesReq {
    op: Operation!
    path: String!
    value: [String!]!
}

input AddOrderReq {
    address: String!
    nearby_landmark: String!
    product_id: ID!
    quantity: Int!
}

input CreatePaymentIntentReq {
    amount: Int!
    currency: String!
    metadata: MetaData!
}

input UpdatePaymentIntentReq {
    payment_method: String!
}

input ConfirmPaymentIntentReq {
    payment_intent_id: String!
    amount: Int!
}

input PaymentWebhookEventReq {
    id: ID!
    type: String!
    data: PaymentWebhookInputData!
}


type Query {
    # Favorites
    getAllUserFavorites: GetAllUserFavoritesRes!
    # Carts
    getUserCarts: GetUserCartsRes!
    # Products
    getProducts(req: GetProductsReq): GetProductsRes!
    getProduct(product_id: ID!): GetProductRes!
    # Orders
    getOrders(req: GetOrdersReq): GetOrdersRes!
    getUserOrders: GetUserOrdersRes!
    getOrder(order_id: ID!): GetOrderRes!
}

type Mutation {
    # Auth
    signIn(req: SignInReq!): SignInRes!
    signOut: SignOutRes!

    # User
    signUp(req: SignUpReq!): SignUpRes!
    forgotPassword(req: ForgotPasswordReq!): ForgotPasswordRes!
    resetPassword(req: ResetPasswordReq!): ResetPasswordRes!

    # Favorites
    addFavorite(req: AddFavoriteReq!): AddFavoriteRes!
    removeFavorite(req: DeleteFavoriteReq!): DeleteFavoriteRes!

    # Carts
    addCart(req: AddCartReq!): AddCartRes!
    updateCart(cart_Id: ID!, req: UpdateCartReq!): UpdateCartRes!
    removeCart(cart_Id: ID!): RemoveCartRes!



    # Orders
    addOrder(req: AddOrderReq): AddOrderRes!

    # Payments
    createPaymentIntent(req: CreatePaymentIntentReq!): CreatePaymentIntentRes!
    updatePaymentIntent(req: UpdatePaymentIntentReq!): UpdatePaymentIntentRes!
    confirmPaymentIntent(req: ConfirmPaymentIntentReq!): ConfirmPaymentIntentRes!
    handlePaymentWebhook(req: PaymentWebhookEventReq!): PaymentWebhookRes!
}

type ManagerMutation {
    # Products
    addProduct(req: AddProductReq!): AddProductRes!
    updateProduct(product_id: ID!, req: UpdateProductReq!): UpdateProductRes!
    removeProduct(product_id: ID!): RemoveProductRes!
    updateProductCategories(
        product_id: ID!
        req: UpdateProductCategoriesReq!
    ): UpdateProductCategoriesRes!
    updateProductImages(
        product_id: ID!
        req: UpdateProductImagesReq!
    ): UpdateProductImagesRes!
}


# GraphQL Editor: https://academy.graphqleditor.com/?lesson=graph